import { TranslationStructure } from './types';

export const TRANSLATIONS: Record<'vi' | 'en', TranslationStructure> = {
  vi: {
    nav: {
      home: 'Trang Chủ',
      about: 'Giới Thiệu',
      services: 'Dịch Vụ',
      gallery: 'Thư Viện',
      contact: 'Liên Hệ',
      bookNow: 'Đặt Lịch Ngay',
    },
    home: {
      heroTitle: 'Nơi Cảm Xúc Thăng Hoa',
      heroSubtitle: 'Quang Thanh Studio - Chuyên nghiệp trong từng giai điệu, tinh tế trong từng khung hình.',
      cta: 'Khám Phá Dịch Vụ',
      featuredService: 'Dịch Vụ Nổi Bật',
    },
    about: {
      title: 'Về Chúng Tôi',
      storyTitle: 'Hành Trình Nghệ Thuật',
      storyText: 'Được thành lập với niềm đam mê cháy bỏng dành cho âm nhạc và nhiếp ảnh, Quang Thanh Studio đã phát triển từ một phòng thu nhỏ tại Vũng Tàu thành một trong những đơn vị truyền thông sáng tạo hàng đầu tại miền Nam. Chúng tôi tin rằng mỗi khách hàng đều có một câu chuyện riêng, và sứ mệnh của chúng tôi là kể lại câu chuyện đó một cách chân thực và nghệ thuật nhất.',
      teamTitle: 'Đội Ngũ Sáng Tạo',
      teamText: 'Tập hợp những kỹ sư âm thanh, nhiếp ảnh gia và quay phim giàu kinh nghiệm. Chúng tôi không chỉ làm việc bằng kỹ thuật mà còn bằng cả trái tim.',
      statClients: 'Khách Hàng',
      statYears: 'Năm Kinh Nghiệm',
      statProjects: 'Dự Án',
    },
    services: {
      title: 'Dịch Vụ Của Chúng Tôi',
      musicTitle: 'Thu Âm & Sản Xuất Âm Nhạc',
      musicDesc: 'Phòng thu tiêu chuẩn quốc tế với trang thiết bị hiện đại. Dịch vụ phối khí, mixing và mastering chuyên nghiệp cho ca sĩ và nghệ sĩ.',
      weddingTitle: 'Quay Chụp Phóng Sự Cưới',
      weddingDesc: 'Ghi lại những khoảnh khắc thiêng liêng nhất. Phong cách Pre-wedding lãng mạn và phóng sự cưới (Journalism) chân thực, giàu cảm xúc.',
      eventTitle: 'Truyền Thông Sự Kiện',
      eventDesc: 'Giải pháp hình ảnh toàn diện cho doanh nghiệp. Quay phim sự kiện, livestream, chụp ảnh profile doanh nghiệp và quảng cáo.',
      learnMore: 'Xem Chi Tiết',
    },
    gallery: {
      title: 'Thư Viện Hình Ảnh',
      categoryAll: 'Tất Cả',
      categoryMusic: 'Âm Nhạc',
      categoryWedding: 'Cưới Hỏi',
      categoryEvent: 'Sự Kiện',
    },
    contact: {
      title: 'Liên Hệ Với Chúng Tôi',
      formTitle: 'Gửi Yêu Cầu Đặt Lịch',
      name: 'Họ và Tên',
      email: 'Email',
      phone: 'Số Điện Thoại',
      serviceType: 'Dịch Vụ Quan Tâm',
      message: 'Lời Nhắn',
      submit: 'Gửi Đi',
      locations: 'Địa Chỉ Studio',
      vungTau: 'Thành phố Vũng Tàu',
      hcmc: 'Thành phố Hồ Chí Minh',
      socials: 'Mạng Xã Hội',
    },
    footer: {
      rights: '© 2024 Quang Thanh Studio. Bảo lưu mọi quyền.',
    },
  },
  en: {
    nav: {
      home: 'Home',
      about: 'About',
      services: 'Services',
      gallery: 'Gallery',
      contact: 'Contact',
      bookNow: 'Book Session',
    },
    home: {
      heroTitle: 'Where Emotions Resonate',
      heroSubtitle: 'Quang Thanh Studio - Professional in every melody, exquisite in every frame.',
      cta: 'Explore Services',
      featuredService: 'Featured Services',
    },
    about: {
      title: 'About Us',
      storyTitle: 'The Artistic Journey',
      storyText: 'Founded with a burning passion for music and photography, Quang Thanh Studio has grown from a small studio in Vung Tau to one of the leading creative media agencies in the South. We believe every client has a unique story, and our mission is to tell that story in the most authentic and artistic way.',
      teamTitle: 'Creative Team',
      teamText: 'A collective of experienced sound engineers, photographers, and videographers. We work not just with technique, but with heart.',
      statClients: 'Clients',
      statYears: 'Years Exp',
      statProjects: 'Projects',
    },
    services: {
      title: 'Our Services',
      musicTitle: 'Music Production & Recording',
      musicDesc: 'International standard studio with modern equipment. Professional arrangement, mixing, and mastering services for singers and artists.',
      weddingTitle: 'Wedding Photography & Videography',
      weddingDesc: 'Capturing the most sacred moments. Romantic Pre-wedding styles and authentic, emotional Journalism wedding coverage.',
      eventTitle: 'Corporate Event Media',
      eventDesc: 'Comprehensive visual solutions for businesses. Event filming, livestreaming, corporate profiling, and advertising photography.',
      learnMore: 'Learn More',
    },
    gallery: {
      title: 'Gallery Showcase',
      categoryAll: 'All',
      categoryMusic: 'Music',
      categoryWedding: 'Wedding',
      categoryEvent: 'Events',
    },
    contact: {
      title: 'Get In Touch',
      formTitle: 'Book a Session',
      name: 'Full Name',
      email: 'Email Address',
      phone: 'Phone Number',
      serviceType: 'Service of Interest',
      message: 'Message',
      submit: 'Send Request',
      locations: 'Studio Locations',
      vungTau: 'Vung Tau City',
      hcmc: 'Ho Chi Minh City',
      socials: 'Social Media',
    },
    footer: {
      rights: '© 2024 Quang Thanh Studio. All rights reserved.',
    },
  },
};